In [1]:
#Load Tensorflow
import tensorflow as tf
tf.set_random_seed(42)

c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\hp\appdata\local\pr

In [2]:
#Collect Data
#from keras.datasets import cifar10
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

In [3]:
#z-score
import numpy as np
mean = np.mean(x_train,axis=(0,1,2,3))
std = np.std(x_train,axis=(0,1,2,3))
x_train = (x_train-mean)/(std)
x_test = (x_test-mean)/(std)

In [4]:
#Convert Output label to multiple values
y_train = tf.keras.utils.to_categorical(y_train, num_classes=10)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=10)

In [5]:
#Build The Graph
#Initialize model, reshape, normalize the data
model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Flatten())

model.add(tf.keras.layers.BatchNormalization())
print(y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [6]:
#Apply ReLU and Dropout
#Hidden layers
model.add(tf.keras.layers.Dense(500, activation='elu', name='Layer_1'))
model.add(tf.keras.layers.Dense(300, activation='elu', name='Layer_2'))

#Dropout layer
model.add(tf.keras.layers.Dropout(0.5))

#Hidden layers
model.add(tf.keras.layers.Dense(120, activation='elu', name='Layer_3'))
model.add(tf.keras.layers.Dense(90, activation='elu', name='Layer_4'))

#Dropout layer
model.add(tf.keras.layers.Dropout(0.3))


In [7]:
#Output Layer
model.add(tf.keras.layers.Dense(10, activation ='softmax', name ='Output'))

In [8]:
#Adam Optimizer
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [9]:
#Logging data for Tensorboard
tensorboard = tf.keras.callbacks.TensorBoard(log_dir = '/tmp/cifar10/cif10_v1')

In [10]:
#Train the model
model.fit(x_train, y_train,
         validation_data = (x_test,y_test),
         callbacks = [tensorboard],
         epochs = 10,
         batch_size = 64)

Train on 50000 samples, validate on 10000 samples
Epoch 1/10
50000/50000 [==============================] - 57s 1ms/step - loss: 2.0506 - acc: 0.3047 - val_loss: 1.5772 - val_acc: 0.4307
Epoch 2/10
50000/50000 [==============================] - 54s 1ms/step - loss: 1.6762 - acc: 0.4017 - val_loss: 1.4897 - val_acc: 0.4624
Epoch 3/10
50000/50000 [==============================] - 52s 1ms/step - loss: 1.5538 - acc: 0.4475 - val_loss: 1.4390 - val_acc: 0.4865
Epoch 4/10
50000/50000 [==============================] - 47s 943us/step - loss: 1.4791 - acc: 0.4739 - val_loss: 1.3820 - val_acc: 0.5095
Epoch 5/10
50000/50000 [==============================] - 45s 901us/step - loss: 1.4215 - acc: 0.4943 - val_loss: 1.3745 - val_acc: 0.5155
Epoch 6/10
50000/50000 [==============================] - 45s 906us/step - loss: 1.3723 - acc: 0.5136 - val_loss: 1.3469 - val_acc: 0.5205
Epoch 7/10
50000/50000 [==============================] - 45s 904us/step - loss: 1.3239 - acc: 0.5296 - val_loss: 1.3120 -